# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github   # Must match the pom.xml distributionManagement/server id
        settings-path: ${{ github.workspace }}

    # Build bookstore-server
    - name: Build bookstore-server
      working-directory: ./bookstore-server
      run: mvn -B package --file pom.xml

    # Build bookstore-admin
    - name: Build bookstore-admin
      working-directory: ./bookstore-admin
      run: mvn -B package --file pom.xml

    # Build bookstore-client
    - name: Build bookstore-client
      working-directory: ./bookstore-client
      run: mvn -B package --file pom.xml

    # Deploy bookstore-server
    - name: Deploy bookstore-server to GitHub Packages
      working-directory: ./bookstore-server
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Deploy bookstore-admin
    - name: Deploy bookstore-admin to GitHub Packages
      working-directory: ./bookstore-admin
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Deploy bookstore-client
    - name: Deploy bookstore-client to GitHub Packages
      working-directory: ./bookstore-client
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
