# This workflow will build a package using Maven.
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Build bookstore-server
    - name: Build bookstore-server
      working-directory: ./bookstore-server
      run: mvn -B package --file pom.xml

    # Start RPC server in the background
    - name: Start RPC server
      working-directory: ./bookstore-server
      run: |
        mvn exec:java -Dexec.mainClass="rpc.RPCServer" &
        sleep 10

    # Build bookstore-admin
    - name: Build bookstore-admin
      working-directory: ./bookstore-admin
      run: mvn -B package --file pom.xml

    # Build bookstore-user
    - name: Build bookstore-user
      working-directory: ./bookstore-user
      run: mvn -B package --file pom.xml
